### ISSUE TITLE
Can not configure

### ISSUE THREAD

**Issue by lecrams** [c-st/auto_areas#37]
## System Information

version | core-2023.5.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 6.1.25
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1294
Downloaded Repositories | 57
HACS Data | ok

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 26

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | August 1, 2023 at 2:00 AM
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-10.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.1
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 117.3 GB
disk_used | 38.0 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.107.2), AppDaemon (0.13.0), File editor (5.6.0), Glances (0.19.2), Mosquitto broker (6.2.1), Samba share (10.0.1), Terminal & SSH (9.7.0), Log Viewer (0.15.1), ESPHome (2023.5.3), Studio Code Server (5.6.0), Rhasspy Assistant (2.5.11), Dutch TTS voice (rdh) (1.0.3), FTP (4.7.0), InfluxDB (4.7.0), Grafana (8.3.0), Music Assistant BETA (2.0.0b30), Node-RED (14.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 30
views | 16
mode | yaml

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 13, 2023 at 2:22 PM
-- | --
current_recorder_run | May 23, 2023 at 3:58 PM
estimated_db_size | 1624.13 MiB
database_engine | sqlite
database_version | 3.40.1

</details>

<details><summary>Sonoff</summary>

version | 3.5.1 (122751c)
-- | --
cloud_online | 1 / 2
local_online | 1 / 1

</details>
[home-assistant_2023-05-23T14-05-41.282Z.log](https://github.com/c-st/auto_areas/files/11544962/home-assistant_2023-05-23T14-05-41.282Z.log)

<details><summary>Xiaomi MIoT</summary>

logged_in | true
-- | --
can_reach_micloud_server | ok
accounts_count | 1
account_devices_count | 4
added_devices | 1

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When I try to configure an area I get the following error:
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### Reproduction steps

1. try to configure an area
2.
3.
...

### Debug logs

```text
see attachment
```

### Diagnostics dump

NA

**Comment by c-st** [comment]
Are you running v2.2.6 of auto_areas? From the logs you provided I cannot find any log messages from the extension unfortunately. So that makes it difficult to see what the problem could be. 

Can you make sure that you have enabled debug logs for auto_areas and upload the complete home assistant logfile:
```configuration.yaml
logger:
  default: info
  logs:
    custom_components.auto_areas: debug
```

**Comment by lecrams** [comment]
I am using v2.2.6 . Full logs attached
[home-assistant_2023-05-24T07-18-00.415Z.log](https://github.com/c-st/auto_areas/files/11551568/home-assistant_2023-05-24T07-18-00.415Z.log)

**Comment by c-st** [comment]
Ah that's good. Now there are some errors:
```
2023-05-24 09:12:42.598 INFO (MainThread) [custom_components.auto_areas] 🤖 Auto Area "Hal" ({})
2023-05-24 09:12:42.599 INFO (MainThread) [custom_components.auto_areas] 🤖 Auto Area "Keuken" ({})


2023-05-24 09:12:42.640 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up auto_areas platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/auto_areas/binary_sensor.py", line 34, in async_setup_entry
    async_add_entities([PresenceBinarySensor(auto_area)])
  File "/config/custom_components/auto_areas/binary_sensor.py", line 44, in __init__
    self.presence_entities: list[str] = self.get_presence_entities()
  File "/config/custom_components/auto_areas/binary_sensor.py", line 86, in get_presence_entities
    for entity in self.auto_area.get_valid_entities():
  File "/config/custom_components/auto_areas/auto_area.py", line 91, in get_valid_entities
    for entity in get_all_entities(
  File "/config/custom_components/auto_areas/ha_helpers.py", line 20, in get_all_entities
    if get_area_id(entity, device_registry) != area_id:
  File "/config/custom_components/auto_areas/ha_helpers.py", line 42, in get_area_id
    device = device_registry.devices[entity.device_id]
  File "/usr/local/lib/python3.10/collections/__init__.py", line 1106, in __getitem__
    raise KeyError(key)
KeyError: '0fd1415222328df54418496623f1e778'
2023-05-24 09:12:42.646 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up auto_areas platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/auto_areas/sensor.py", line 19, in async_setup_entry
    async_add_entities([IlluminanceSensor(auto_area)])
  File "/config/custom_components/auto_areas/sensor.py", line 28, in __init__
    self.illuminance_entities: list[str] = self.get_illuminance_entities()
  File "/config/custom_components/auto_areas/sensor.py", line 73, in get_illuminance_entities
    for entity in self.auto_area.get_valid_entities():
  File "/config/custom_components/auto_areas/auto_area.py", line 91, in get_valid_entities
    for entity in get_all_entities(
  File "/config/custom_components/auto_areas/ha_helpers.py", line 20, in get_all_entities
    if get_area_id(entity, device_registry) != area_id:
  File "/config/custom_components/auto_areas/ha_helpers.py", line 42, in get_area_id
    device = device_registry.devices[entity.device_id]
  File "/usr/local/lib/python3.10/collections/__init__.py", line 1106, in __getitem__
    raise KeyError(key)
KeyError: '0fd1415222328df54418496623f1e778'
2023-05-24 09:12:42.650 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up auto_areas platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/auto_areas/binary_sensor.py", line 34, in async_setup_entry
    async_add_entities([PresenceBinarySensor(auto_area)])
  File "/config/custom_components/auto_areas/binary_sensor.py", line 44, in __init__
    self.presence_entities: list[str] = self.get_presence_entities()
  File "/config/custom_components/auto_areas/binary_sensor.py", line 86, in get_presence_entities
    for entity in self.auto_area.get_valid_entities():
  File "/config/custom_components/auto_areas/auto_area.py", line 91, in get_valid_entities
    for entity in get_all_entities(
  File "/config/custom_components/auto_areas/ha_helpers.py", line 20, in get_all_entities
    if get_area_id(entity, device_registry) != area_id:
  File "/config/custom_components/auto_areas/ha_helpers.py", line 42, in get_area_id
    device = device_registry.devices[entity.device_id]
  File "/usr/local/lib/python3.10/collections/__init__.py", line 1106, in __getitem__
    raise KeyError(key)
KeyError: '0fd1415222328df54418496623f1e778'
2023-05-24 09:12:42.652 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up auto_areas platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/auto_areas/sensor.py", line 19, in async_setup_entry
    async_add_entities([IlluminanceSensor(auto_area)])
  File "/config/custom_components/auto_areas/sensor.py", line 28, in __init__
    self.illuminance_entities: list[str] = self.get_illuminance_entities()
  File "/config/custom_components/auto_areas/sensor.py", line 73, in get_illuminance_entities
    for entity in self.auto_area.get_valid_entities():
  File "/config/custom_components/auto_areas/auto_area.py", line 91, in get_valid_entities
    for entity in get_all_entities(
  File "/config/custom_components/auto_areas/ha_helpers.py", line 20, in get_all_entities
    if get_area_id(entity, device_registry) != area_id:
  File "/config/custom_components/auto_areas/ha_helpers.py", line 42, in get_area_id
    device = device_registry.devices[entity.device_id]
  File "/usr/local/lib/python3.10/collections/__init__.py", line 1106, in __getitem__
    raise KeyError(key)
KeyError: '0fd1415222328df54418496623f1e778'
```

It looks like one of your devices (with ID '0fd1415222328df54418496623f1e778 ') can not be looked up in the device registry.

I can push a fix to make it more robust in this regard. But as I'm a bit limited at the moment (on vacation with only an iPad 😅) that might take a few days.

**Comment by c-st** [comment]
@lecrams I created a new release which includes a fix for your issue. Would you mind trying it out? It’s v2.2.7 and marked as beta release (so you might need to turn on the checkbox in HACS).

**Comment by lecrams** [comment]
Now its working! Thanks for the fast solution

**Comment by c-st** [comment]
Nice! Thanks for reporting it.
